eCart/Areas/Store/Controllers/CartDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using eCartDbLayer;
using eCartModels;
using eCartServices;
using Microsoft.AspNet.Identity;

namespace eCart.Areas.Store.Controllers
{
    public class CartDetailsController : Controller
    {
        StoreFactory store = new StoreFactory();
       
        // GET: Store/CartDetails/{cartId}
        //public ActionResult Index(int id)
        //{
        //    return View();
        //}

        // GET: Store/CartDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userId = HttpContext.User.Identity.GetUserId();
            if (userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CartDetail cartDetail = store.CartMgr.GetCartDetail((int)id);

            ViewBag.StoreId = cartDetail.StoreDetailId;
            ViewBag.Store = cartDetail.StoreDetail.Name;
            ViewBag.PaymentReceiverList = store.RefDbLayer.GetPaymentReceivers().ToList();
            ViewBag.PaymentStatusList = store.RefDbLayer.GetPaymentStatus().ToList();
            ViewBag.PaymentPartyList = store.RefDbLayer.GetPaymentParties().ToList();
            ViewBag.PaymentDetails = store.CartMgr.GetCartPaymentDetails((int)id);
            ViewBag.CartDelivery = store.CartMgr.GetCartDeliveries((int)id);
            ViewBag.RiderList = store.RiderMgr.GetActiveRiders();

            //cart Realease
            ViewBag.StorePickupPoints = new SelectList(store.CartMgr.GetStorePickupPoints(cartDetail.StoreDetailId), "Id", "Address", cartDetail.StorePickupPointId);
            ViewBag.UserDetails = new SelectList(store.RefDbLayer.GetUserDetails().Where(u => u.UserStatusId == 1), "Id", "Name", cartDetail.UserDetailId);
            ViewBag.UserId = userId;
            ViewBag.UserEmail = HttpContext.User.Identity.GetUserName();

            if (cartDetail == null)
            {
                return HttpNotFound();
            }
            return View(cartDetail);
        }


        // GET: Store/CartDetails/Create
        public ActionResult Create()
        {
            //ViewBag.CartStatusId = new SelectList(db.CartStatus, "Id", "Name");
            //ViewBag.StoreDetailId = new SelectList(db.StoreDetails, "Id", "LoginId");
            //ViewBag.StorePickupPointId = new SelectList(db.StorePickupPoints, "Id", "Address");
            //ViewBag.UserDetailId = new SelectList(db.UserDetails, "Id", "UserId");
            return View();
        }

        // POST: Store/CartDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserDetailId,StoreDetailId,CartStatusId,StorePickupPointId")] CartDetail cartDetail)
        {
            if (ModelState.IsValid)
            {
                //db.CartDetails.Add(cartDetail);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.CartStatusId = new SelectList(db.CartStatus, "Id", "Name", cartDetail.CartStatusId);
            //ViewBag.StoreDetailId = new SelectList(db.StoreDetails, "Id", "LoginId", cartDetail.StoreDetailId);
            //ViewBag.StorePickupPointId = new SelectList(db.StorePickupPoints, "Id", "Address", cartDetail.StorePickupPointId);
            //ViewBag.UserDetailId = new SelectList(db.UserDetails, "Id", "UserId", cartDetail.UserDetailId);
            return View(cartDetail);
        }

        // GET: Store/CartDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //CartDetail cartDetail = db.CartDetails.Find(id);
            //if (cartDetail == null)
            //{
            //    return HttpNotFound();
            //}
            //ViewBag.CartStatusId = new SelectList(db.CartStatus, "Id", "Name", cartDetail.CartStatusId);
            //ViewBag.StoreDetailId = new SelectList(db.StoreDetails, "Id", "LoginId", cartDetail.StoreDetailId);
            //ViewBag.StorePickupPointId = new SelectList(db.StorePickupPoints, "Id", "Address", cartDetail.StorePickupPointId);
            //ViewBag.UserDetailId = new SelectList(db.UserDetails, "Id", "UserId", cartDetail.UserDetailId);
            return View();
        }

        // POST: Store/CartDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserDetailId,StoreDetailId,CartStatusId,StorePickupPointId")] CartDetail cartDetail)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(cartDetail).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.CartStatusId = new SelectList(db.CartStatus, "Id", "Name", cartDetail.CartStatusId);
            //ViewBag.StoreDetailId = new SelectList(db.StoreDetails, "Id", "LoginId", cartDetail.StoreDetailId);
            //ViewBag.StorePickupPointId = new SelectList(db.StorePickupPoints, "Id", "Address", cartDetail.StorePickupPointId);
            //ViewBag.UserDetailId = new SelectList(db.UserDetails, "Id", "UserId", cartDetail.UserDetailId);
            return View();
        }

        // GET: Store/CartDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //CartDetail cartDetail = db.CartDetails.Find(id);
            //if (cartDetail == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(cartDetail);

            return View();
        }

        // POST: Store/CartDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //CartDetail cartDetail = db.CartDetails.Find(id);
            //db.CartDetails.Remove(cartDetail);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public bool AddPayment(string date, int partyId, string partyInfo, int receiverId, string receiverInfo, int statusId, decimal amount, int cartDetailId)
        {
            try
            {
                var storeMgr = store.StoreMgr;
                storeMgr.addPaymentDetails(date, partyId, partyInfo, receiverId, receiverInfo, statusId, amount, cartDetailId);
                return true;
            }
            catch
            {
                return false;
            }
        }

        [HttpGet]
        public JsonResult SetCartStatus(int id, int statusId)
        {
            var cartMgr = store.CartMgr;
            var userid =  HttpContext.User.Identity.GetUserId();
            var response = cartMgr.SetDBCartStatus(id,statusId, userid.ToString()); 

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public bool AddDeliveryRider(int cartDetailId, DateTime date, string address, int riderId, string remarks)
        {
            try
            {
                var cartMgr = store.CartMgr;
                cartMgr.AddDeliveryDetails(cartDetailId, date, address, riderId, remarks);
                return true;
            }
            catch
            {
                return false;
            }
        }

        [HttpPost]
        public void UpdateDeliveryRider(int id, int cartDetailId, DateTime date, string address, int riderId, string remarks)
        {
            var cartMgr = store.CartMgr;

            var cartDelivery = new CartDelivery
            {
                Id = id,
                Address = address,
                CartDetailId = cartDetailId,
                RiderDetailId = riderId,
                Remarks = remarks,
                dtDelivery = date
            };

            cartMgr.updateCartDelivery(cartDelivery);
        }

        public void DeleteCartDelivery(int id)
        {
            var cartMgr = store.CartMgr;
            cartMgr.removeCartdelivery(id);
        }

        #region CartHistory
        public ActionResult CartHistory(int? id)
        {
            if (id != null)
            {
                var cartMgr = store.CartMgr;
                var cartHistory = cartMgr.getCartHistory((int)id);
                ViewBag.StoreId = id;
                return View(cartHistory);
            }

            return RedirectToAction("Index", new { id = id });
        }

        [HttpGet]
        public JsonResult GetCartDeliveryActivities(int id)
        {
            var cartMgr = store.CartMgr;
            var cartDeliveryActivity = cartMgr.getCartDeliveryActivities(id).Select(c => new { Date = c.dtActivity.ToString(), Activity = c.CartActivityType.Name });

            return Json(cartDeliveryActivity, JsonRequestBehavior.AllowGet);
        }


        #endregion

        #region cart release
        [HttpPost]

eCart/Areas/Store/Controllers/CashierController.cs
using eCartServices;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCart.Areas.Store.Controllers
{
    public class CashierController : Controller
    {
        private StoreFactory store = new StoreFactory();
        private int CASHIER = 3;

        // GET: Store/Cashier
        public ActionResult Index()
        {
            var userid = HttpContext.User.Identity.GetUserId();
            var storeDetail = store.StoreMgr.GetStoreDetailByLoginId(userid);
            var storeId = 0;
            if (storeDetail != null)
            {
                storeId = storeDetail.Id;
            }
            else
            {
                var storeUser = store.StoreMgr.GetStoreUser(userid);
                storeDetail = storeUser.StoreDetail;
                if (storeDetail != null)
                {
                    storeId = storeDetail.Id;
                    var isUserCashier = store.StoreMgr.CheckStoreUserType(userid, CASHIER);
                    if (!isUserCashier)
                        return RedirectToAction("NoUserStore");
                }
                else
                {
                    return RedirectToAction("NoUserStore");
                }

            }

            ViewBag.StoreId = storeId;
            ViewBag.StoreImage = storeDetail.StoreImages.FirstOrDefault().ImageUrl;
            ViewBag.User = HttpContext.User.Identity.Name;
            return View();
        }

        [HttpPost]
        public ActionResult Index(int cartId)
        { 
            if (ModelState.IsValid )
            {

                var userid = HttpContext.User.Identity.GetUserId();

                var storeDetail = store.StoreMgr.GetStoreDetailByLoginId(userid);
                var storeId = 0;
                if (storeDetail != null)
                {
                    storeId = storeDetail.Id;
                }
                else
                {
                    var storeUser = store.StoreMgr.GetStoreUser(userid);
                    storeDetail = storeUser.StoreDetail;
                    if (storeDetail != null)
                    {
                        storeId = storeDetail.Id;
                        var isUserCashier = store.StoreMgr.CheckStoreUserType(userid, CASHIER);
                        if (!isUserCashier)
                            return RedirectToAction("NoUserStore");
                    }
                    else
                    {
                        return RedirectToAction("NoUserStore");
                    }

                }

                var cart = store.CartMgr.GetCartDetail(cartId);
                ViewBag.StoreId = storeId;
                ViewBag.StoreImage = storeDetail.StoreImages.FirstOrDefault().ImageUrl;
                ViewBag.User = HttpContext.User.Identity.Name;
                if (cart != null && cart.StoreDetailId == storeDetail.Id)
                {
                    return RedirectToAction("Index", new { id = cartId });
                    //return View();
                }
                else
                {
                    ModelState.AddModelError("", "No existing cart found");
                    return RedirectToAction("Index", new { id = cartId });
                }
            }

            return View();
        }

        public ActionResult CartDetails(int id)
        {

            var userid = HttpContext.User.Identity.GetUserId();
            var storeDetail = store.StoreMgr.GetStoreDetailByLoginId(userid);
            if(storeDetail == null)
            {
                var storeUser = store.StoreMgr.GetStoreUser(userid);
                storeDetail = storeUser.StoreDetail;
            }

            var cart = store.CartMgr.GetCartDetail(id);
            if (cart != null && cart.StoreDetailId == storeDetail.Id)
            {

                ViewBag.StoreId = cart.StoreDetailId;
                ViewBag.Store = cart.StoreDetail.Name;
                ViewBag.PaymentReceiverList = store.RefDbLayer.GetPaymentReceivers().ToList();
                ViewBag.PaymentStatusList = store.RefDbLayer.GetPaymentStatus().ToList();
                ViewBag.PaymentPartyList = store.RefDbLayer.GetPaymentParties().ToList();
                ViewBag.PaymentDetails = store.CartMgr.GetCartPaymentDetails((int)id);
                ViewBag.User = HttpContext.User.Identity.Name;
                ViewBag.HaveCartDetails = true;
                return View(cart);
            }

            return View();
        }

    }
}

eCart/Areas/Store/Controllers/StoreKioskOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eCartModels;
using eCartServices;

namespace eCart.Areas.Store.Controllers
{
    public class StoreKioskOrdersController : Controller
    {
        private StoreFactory store = new StoreFactory();

        // GET: Store/StoreKioskOrders
        public ActionResult Index(int? id, int? orderStatus)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var storeKioskOrders = store.CartMgr.GetStoreKioskOrderList((int)id); 
            ViewBag.StoreId = id;

            return View(storeKioskOrders.ToList());
        }

    }
}

eCart/Areas/Store/Controllers/StorePickupPartnersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eCartDbLayer;
using eCartModels;
using eCartServices;

namespace eCart.Areas.Store.Controllers
{
    public class StorePickupPartnersController : Controller
    {
        private StoreFactory store = new StoreFactory();

        // GET: Store/StorePickupPartners/{storeId}
        public ActionResult Index(int id)
        {
            var partneredList = store.StoreMgr.GetStorePickupPartners(id).Select(s => s.StorePickupPointId).ToList();
            var StorePickupPoints = store.StoreMgr.GetStorePickupPoints(id);
            var pickupPointsList = store.StoreMgr.GetStorePickupPoints().Where(s=>s.StorePickupStatusId == 1).ToList();


            ViewBag.StoreId = id;
            ViewBag.PickupPoints = pickupPointsList.Except(StorePickupPoints).Where(s => !partneredList.Contains(s.Id)).OrderBy(s => s.StoreDetailId);

            var storePickupPartners = store.StoreMgr.GetStorePickupPartners(id);
            return View(storePickupPartners.ToList());
        }

        [HttpGet]
        public bool AddPartner(int id, int storeId)
        {
            try
            {
                StorePickupPartner storePartner = new StorePickupPartner
                {
                    StoreDetailId = storeId,
                    StorePickupPointId = id
                };

                return store.StoreMgr.AddStorePickupPartner(storePartner);

            } catch {
                return false;
            }
        }

        [HttpPost]
        public bool RemovePartner(int id, int storeId)
        {
            try
            {
                var storePartner = store.StoreMgr.GetStorePickupPartners(storeId).Find(s=>s.Id == id);

                return store.StoreMgr.RemoveStorePickupPartner(storePartner);
            }
            catch
            {
                return false;
            }
        }
    }
}


#region helperClass
public class jsonStorePartner{
        public int Id { get; set; }
        public string StoreName { get; set; }
        public string PickupAddress { get; set; }
    }

#endregion

eCart/Areas/Store/Views/Store/Index.cshtml
@model eCartModels.StoreDetail

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="container-panel col-lg-12 col-md-12 col-sm-12">

        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="col-sm-4 col-md-6 col-lg-3" style="left:20px;">
                @if (Model.StoreImages.FirstOrDefault() != null)
                {
                    var image = Model.StoreImages.FirstOrDefault();
                    <img src="@image.ImageUrl" class="store-logo" />
                }
                else
                {
                    <img src="~/img/placeholders/placeholder-product.png" class="store-logo login-image-side" />
                }
            </div>

            <div class="col-sm-8 col-md-6 col-lg-9">
                <h2> @Model.Name </h2>
                <p class="text-muted"> Address: <b>@Model.Address</b> </p>
                <p class="text-muted"> Categories: <b>@Model.StoreCategory.Name</b> </p>
            </div>
        </div>
        @if (ViewBag.IsUserAdmin == true)
        {
            <div class="col-lg-3 col-md-3 col-sm-12">
                <div class="btn-group-vertical" style="width:100%;margin:0;">
                    <a class="btn btn-default" href="@Url.Action("Edit","StoreDetails",new { id = ViewBag.StoreId })">
                        Store Details
                    </a>
                    <a class="btn btn-default" href="@Url.Action("Index","StoreUsers")" style="width:100%;">
                        Store Users
                    </a>
                    <a class="btn btn-default" href="@Url.Action("Index","StoreItems",new { id = ViewBag.StoreId })">
                        Store Items
                    </a>
                    <a class="btn btn-default" href="@Url.Action("Index","StorePickupPoints",new { id = ViewBag.StoreId })" style="width:100%;">
                        Pickup Points
                    </a>
                    <a class="btn btn-default" href="@Url.Action("Index","StorePickupPartners",new { id = ViewBag.StoreId })" style="width:100%;">
                        Pickup Partner
                    </a>
                    <a class="btn btn-default" href="@Url.Action("Index","StoreKiosks", null)" style="width:100%;">
                        Kiosks
                    </a>
                    <a class="btn btn-default" href="@Url.Action("Index","StorePayments",new { id = ViewBag.StoreId })" style="width:100%;">
                        Subscription
                    </a>
                    <a class="btn btn-default" href="@Url.Action("Index","Cashier",new { id = ViewBag.StoreId })" style="width:100%;">
                        Cashier
                    </a>
                </div>
            </div>
        }
        else if (ViewBag.IsUserCashier == true)
        {
            <div class="col-lg-3 col-md-3 col-sm-12">
                <div class="btn-group-vertical" style="width:100%;margin:0;">
                    <a class="btn btn-default" href="@Url.Action("Index","Cashier",new { id = ViewBag.StoreId })" style="width:100%;">
                        Cashier
                    </a>
                </div>
            </div>
        }
    </div>
</div>

@Html.Partial("_PartialCartList", ViewBag.CartList as IEnumerable<eCartModels.CartDetail>, new ViewDataDictionary { { "StoreId", ViewBag.StoreId } })

@Html.Partial("_ModalPayment", null, new ViewDataDictionary { { "PaymentReceiverList", ViewBag.PaymentReceiverList },
    { "PaymentPartyList", ViewBag.PaymentPartyList }, { "PaymentStatusList", ViewBag.PaymentStatusList } })

@section Scripts{
    <script src="~/Areas/Store/Scripts/CartDetails/ModalPayment.js"></script>
    <script>
        $(document).ready(function () { updateFilterStatus(); });

        function updateFilterStatus() {
            var url_string = window.location.href; //window.location.href
            var url = new URL(url_string);
            var cartStatus = url.searchParams.get("cartStatus");

            if (cartStatus != null) {

                switch (cartStatus.toString()) {
                    case '5':
                        $('#cartStatus-Delivered').siblings().removeClass('active');
                        $('#cartStatus-Delivered').addClass('active');
                        break;
                    case '6':
                        $('#cartStatus-Cancelled').siblings().removeClass('active');
                        $('#cartStatus-Cancelled').addClass('active');
                        break;
                    default:
                        $('#cartStatus-Active').siblings().removeClass('active');
                        $('#cartStatus-Active').addClass('active');
                        break;
                }

            }
        }

        function AutoFillPaymentDetails(shopperName) {
            $("#payment-partyInfo").val(shopperName);
            $("#payment-receiverInfo").val('@ViewBag.User');
            $("#payment-status").val(2);
            
        }
    </script>
}

eCart/Areas/Store/Views/Store/NoUserStore.cshtml
<div>
    No Store defined for the user.
</div>

eCart/Areas/Store/Views/Store/StoreHeader.cshtml
@model eCartModels.StoreDetail

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="container-panel col-lg-12 col-md-12 col-sm-12">

        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="col-sm-4 col-md-6 col-lg-3" style="left:20px;">
                @if (Model.StoreImages.FirstOrDefault() != null)
                {
                    var image = Model.StoreImages.FirstOrDefault();
                    <img src="@image.ImageUrl" class="store-logo" />
                }
                else
                {
                    <img src="~/img/placeholders/placeholder-product.png" class="store-logo login-image-side" />
                }
            </div>

            <div class="col-sm-8 col-md-6 col-lg-9">
                <h2> @Model.Name </h2>
                <p class="text-muted"> Address: <b>@Model.Address</b> </p>
                <p class="text-muted"> Categories: <b>@Model.StoreCategory.Name</b> </p>
            </div>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-12">
            <div class="btn-group-vertical" style="width:100%;margin:0;">
                <a class="btn btn-default" href="@Url.Action("Edit","StoreDetails",new { id = ViewBag.StoreId })">
                    Store Details
                </a>
                <a class="btn btn-default" href="@Url.Action("Index","StoreItems",new { id = ViewBag.StoreId })">
                    Store Items
                </a>
                <a class="btn btn-default" href="@Url.Action("Index","StorePickupPoints",new { id = ViewBag.StoreId })" style="width:100%;">
                    Pickup Points
                </a>
                <a class="btn btn-default" href="@Url.Action("Index","StorePickupPartners",new { id = ViewBag.StoreId })" style="width:100%;">
                    Pickup Partner
                </a>
                <a class="btn btn-default" href="@Url.Action("Index","StorePayments",new { id = ViewBag.StoreId })" style="width:100%;">
                    Subscription
                </a>
            </div>
        </div>
    </div>
</div>

eCart/Areas/Store/Views/Store/_PartialCartList.cshtml
@model IEnumerable<eCartModels.CartDetail>



<div class="col-lg-12" style="margin:10px 0px;">
    <h2> Active Shoppers Carts </h2>
    <div class="col-lg-4" style="margin-top:5px;">
        <div class="btn-group">
            <a class="btn btn-default active" id="cartStatus-Active" href="@Url.Action("Index", "Store", new { id = ViewBag.StoreId, cartStatus = 1 })"> Active </a>
            <a class="btn btn-default" id="cartStatus-Delivered" href="@Url.Action("Index", "Store", new { id = ViewBag.StoreId, cartStatus = 5 })"> Delivered </a>
            <a class="btn btn-default" id="cartStatus-Cancelled" href="@Url.Action("Index", "Store", new { id = ViewBag.StoreId, cartStatus = 6 })"> Cancelled </a>
        </div>
    </div>

    <div class="col-lg-offset-5 col-lg-3" style="margin-top:5px;">
        <div class="btn-group">
            @*<a class="btn btn-default active" > Online Orders </a>*@
            @*<a class="btn btn-default" href="@Url.Action("Index", "StoreKioskOrders", new { id = ViewBag.StoreId })"> Kiosk Orders </a>*@
        </div>
    </div>
</div>

<div class="panel panel-default col-lg-12">
    <table class="table">
        <thead>
            <tr style="font-weight:bold;">
                <td style="width:100px;"> Cart&nbsp;Id </td>
                <td style="min-width:120px;"> Status </td>
                <td> Shopper </td>
                <td> Contact # </td>
                <td> Delivery Type </td>
                <td> Pickup Date </td>
                <td> Total Items </td>
                <td> Pickup Location </td>
                <td> Total Amount </td>
                <td> Payment </td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @{
                var itemCount = 0;
                decimal totalAmount = 0;
            }
            @foreach (var cart in Model)
            {
                foreach (var item in cart.CartItems)
                {
                    itemCount++;
                    totalAmount += item.ItemQty * item.StoreItem.UnitPrice;
                }
                <tr>
                    <td>

                        @if (cart.DeliveryType == "Kiosk") //Kiosk
                        {
                            <img src="~/img/store/icons/purchase-order-48.png" class="store-cart-status-icon" />
                        }
                        else
                        {
                            <img src="~/img/store/icons/delivery-40.png" class="store-cart-status-icon" />
                        }

                        @cart.Id.ToString("#0000")
                    </td>
                    <td>

                        @if (cart.CartStatusId == 2) //processing
                        {
                            <img src="~/img/store/icons/submit-48.png" class="store-cart-status-icon" />
                        }
                        @if (cart.CartStatusId == 3) //processing
                        {
                            <img src="~/img/store/icons/cart-process-40.png" class="store-cart-status-icon" />
                        }
                        else if (cart.CartStatusId == 4) //active
                        {
                            <img src="~/img/store/icons/cart-ok-40.png" class="store-cart-status-icon" />
                        }

                        @cart.CartStatu.Name
                    </td>
                    <td>
                        @if (cart.DeliveryType == "Kiosk")
                        {
                            Html.RenderAction("getKioskOrderName", new { id = cart.Id });
                        }
                        else
                        {
                            @cart.UserDetail.Name
                        }
                    </td>
                    <td>

                        @if (cart.DeliveryType == "Kiosk")
                        {
                           
                        }
                        else
                        {
                            @cart.UserDetail.Mobile
                        }
                    </td>
                    <td>
                        @cart.DeliveryType
                    </td>
                    <td>
                        @if (cart.DeliveryType == "Kiosk")
                        {

                        }
                        else
                        {
                            @cart.UserDetail.Name
                        }
                    </td>
                    <td>
                        @cart.CartItems.Count()
                    </td>
                    <td>
                        @if (cart.DeliveryType == "Kiosk")
                        {

                        }
                        else
                        {
                            @cart.StorePickupPoint.Address
                        }

                    </td>
                    <td>
                        @{decimal amount = 0;}
                        @foreach (var item in cart.CartItems)
                        {

                            amount += item.StoreItem.UnitPrice * item.ItemQty;

                        }
                        <span>
                            @amount.ToString("0.00")
                        </span>
                    </td>
                    <td>
                        <span id="table-payment-@cart.Id">
                            @if (cart.PaymentDetails.FirstOrDefault() != null)
                            {
                                @cart.PaymentDetails.LastOrDefault().Amount.ToString("0.00") <br />
                                @cart.PaymentDetails.LastOrDefault().PaymentStatu.Name
                            }
                        </span>
                    </td>
                    <td>
                        @Html.ActionLink("View Cart", "Details", "CartDetails", new { id = cart.Id }, new { @class = "btn btn-primary" })
                        <button class="btn btn-default" data-target="#PaymentModal" data-toggle="modal" id="payment-btn" onclick="SetPaymentCart(@cart.Id, '@cart.UserDetail.Name',  '@amount.ToString("0.00")')"> Payment </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>