eCart/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCart.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            var userId = HttpContext.User.Identity.GetUserId();
            if (userId != null)
            {
                return View();
            }

            return RedirectToAction("Index", "Home", new { area = "" });
        }

        public ActionResult MasterFiles()
        {
            return View();
        }
    }
}

eCart/Areas/Admin/Controllers/StoreDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using eCartModels;
using eCartServices;
using Microsoft.Ajax.Utilities;

namespace eCart.Areas.Admin.Controllers
{
    public class StoreDetailsController : Controller
    {
        private StoreFactory store = new StoreFactory();

        // GET: Admin/StoreDetails
        public ActionResult Index()
        {
            var storeDetails = store.RefDbLayer.GetStoreDetails().Include(s => s.MasterArea).Include(s => s.MasterCity).Include(s => s.StoreCategory).Include(s => s.StoreStatu);
            return View(storeDetails.ToList());
        }

        // GET: Admin/StoreDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StoreDetail storeDetail = store.RefDbLayer.GetStoreDetails().Where(s=>s.Id == id).FirstOrDefault();
            if (storeDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.StoreKiosks = store.StoreMgr.GetStoreKiosks(storeDetail.Id);

            return View(storeDetail);
        }

        // GET: Admin/StoreDetails/Create
        public ActionResult Create()
        {

            ViewBag.LoginId = new SelectList(store.RefDbLayer.GetAspNetUsers().ToList());
            ViewBag.MasterAreaId = new SelectList(store.RefDbLayer.GetMasterAreas(), "Id", "Name");
            ViewBag.MasterCityId = new SelectList(store.RefDbLayer.GetMasterCities(), "Id", "Name");
            ViewBag.StoreCategoryId = new SelectList(store.RefDbLayer.GetStoreCategories(), "Id", "Name");
            ViewBag.StoreStatusId = new SelectList(store.RefDbLayer.GetStoreStatus(), "Id", "Name");
            return View();
        }

        // POST: Admin/StoreDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,LoginId,Name,Address,Remarks,StoreStatusId,StoreCategoryId,MasterCityId,MasterAreaId")] StoreDetail storeDetail)
        {
            if (ModelState.IsValid)
            {

                if (store.AdminMgr.AddStoreDetails(storeDetail))
                {
                    return RedirectToAction("Index");
                }

            }

            ViewBag.LoginId = new SelectList(store.RefDbLayer.GetAspNetUsers().ToList(), storeDetail.LoginId);
            ViewBag.MasterAreaId = new SelectList(store.RefDbLayer.GetMasterAreas(), "Id", "Name", storeDetail.MasterAreaId);
            ViewBag.MasterCityId = new SelectList(store.RefDbLayer.GetMasterCities(), "Id", "Name", storeDetail.MasterCityId);
            ViewBag.StoreCategoryId = new SelectList(store.RefDbLayer.GetStoreCategories(), "Id", "Name", storeDetail.StoreCategoryId);
            ViewBag.StoreStatusId = new SelectList(store.RefDbLayer.GetStoreStatus(), "Id", "Name", storeDetail.StoreStatusId);
            return View(storeDetail);
        }

        // GET: Admin/StoreDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StoreDetail storeDetail = store.AdminMgr.GetStoreDetail((int)id);
            if (storeDetail == null)
            {
                return HttpNotFound();
            }

            var identityUSers = store.RefDbLayer.GetAspNetUsers();
            List<SelectListItem> userList = new List<SelectListItem>();
            foreach(IdentityUSer user in identityUSers)
            {
                userList.Add(new SelectListItem()
                {
                    Text = user.UserName,
                    Value = user.LoginId
                });
            }
            ViewBag.LoginId = new SelectList(userList,"Value","Text", storeDetail.LoginId);
            ViewBag.MasterAreaId = new SelectList(store.RefDbLayer.GetMasterAreas(), "Id", "Name", storeDetail.MasterAreaId);
            ViewBag.MasterCityId = new SelectList(store.RefDbLayer.GetMasterCities(), "Id", "Name", storeDetail.MasterCityId);
            ViewBag.StoreCategoryId = new SelectList(store.RefDbLayer.GetStoreCategories(), "Id", "Name", storeDetail.StoreCategoryId);
            ViewBag.StoreStatusId = new SelectList(store.RefDbLayer.GetStoreStatus(), "Id", "Name", storeDetail.StoreStatusId);
            return View(storeDetail);
        }

        // POST: Admin/StoreDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,LoginId,Name,Address,Remarks,StoreStatusId,StoreCategoryId,MasterCityId,MasterAreaId")] StoreDetail storeDetail)
        {
            if (ModelState.IsValid)
            {
                
                if (store.AdminMgr.EditStoreDetails(storeDetail))
                {
                    return RedirectToAction("Index");
                }
            }

            var identityUSers = store.RefDbLayer.GetAspNetUsers();
            List<SelectListItem> userList = new List<SelectListItem>();
            foreach (IdentityUSer user in identityUSers)
            {
                userList.Add(new SelectListItem()
                {
                    Text = user.UserName,
                    Value = user.LoginId
                });
            }
            ViewBag.LoginId = new SelectList(userList, "Value", "Text", storeDetail.LoginId);

            ViewBag.MasterAreaId = new SelectList(store.RefDbLayer.GetMasterAreas(), "Id", "Name", storeDetail.MasterAreaId);
            ViewBag.MasterCityId = new SelectList(store.RefDbLayer.GetMasterCities(), "Id", "Name", storeDetail.MasterCityId);
            ViewBag.StoreCategoryId = new SelectList(store.RefDbLayer.GetStoreCategories(), "Id", "Name", storeDetail.StoreCategoryId);
            ViewBag.StoreStatusId = new SelectList(store.RefDbLayer.GetStoreStatus(), "Id", "Name", storeDetail.StoreStatusId);
            return View(storeDetail);
        }

        // GET: Admin/StoreDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StoreDetail storeDetail = store.AdminMgr.GetStoreDetail((int)id);
            if (storeDetail == null)
            {
                return HttpNotFound();
            }
            return View(storeDetail);
        }

        // POST: Admin/StoreDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StoreDetail storeDetail = store.AdminMgr.GetStoreDetail((int)id);

            if (store.AdminMgr.RemovestoreDetails(storeDetail))
            {
                return RedirectToAction("Index");
            }

            return View(storeDetail);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                store.AdminMgr.DbDispose();
            }
            base.Dispose(disposing);
        }


    }
}

eCart/Areas/Admin/Controllers/StoreKiosksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eCartModels;
using eCartServices;

namespace eCart.Areas.Admin.Controllers
{
    public class StoreKiosksController : Controller
    {
        private ecartdbContainer db = new ecartdbContainer();
        private StoreFactory store = new StoreFactory();

        private static List<SelectListItem> SettingsTypes = new List<SelectListItem>()
        {
          new SelectListItem{Text = "Layout-A", Value = "1"},
          new SelectListItem{Text = "Layout-B", Value = "2"},
          new SelectListItem{Text = "Layout-C", Value = "3"}
        };

        // GET: Admin/StoreKiosks
        public ActionResult Index()
        {
            var storeKiosks = store.AdminMgr.GetStoreKioskList();
            return View(storeKiosks.ToList());
        }

        // GET: Admin/StoreKiosks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StoreKiosk storeKiosk = store.AdminMgr.GetStoreKiosk((int)id); 
            if (storeKiosk == null)
            {
                return HttpNotFound();
            }
            return View(storeKiosk);
        }

        // GET: Admin/StoreKiosks/Create
        public ActionResult Create(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.StoreDetailId = new SelectList(db.StoreDetails, "Id", "LoginId", id);
            ViewBag.SettingId = new SelectList(SettingsTypes, "Value", "Text");
            ViewBag.StoreId = id;
            return View();
        }

        // POST: Admin/StoreKiosks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StoreDetailId,KioskName,SettingId")] StoreKiosk storeKiosk)
        {
            if (ModelState.IsValid)
            {
               if(store.AdminMgr.AddStoreKiosk(storeKiosk))
                    return RedirectToAction("Details","StoreDetails", new { id = storeKiosk.StoreDetailId });
            }

            ViewBag.StoreDetailId = new SelectList(db.StoreDetails, "Id", "LoginId", storeKiosk.StoreDetailId);
            ViewBag.SettingId = new SelectList(SettingsTypes, "Value", "Text", storeKiosk.SettingId);
            ViewBag.StoreId = storeKiosk.StoreDetailId;
            return View(storeKiosk);
        }

        // GET: Admin/StoreKiosks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StoreKiosk storeKiosk = store.AdminMgr.GetStoreKiosk((int)id);
            if (storeKiosk == null)
            {
                return HttpNotFound();
            }
            ViewBag.StoreDetailId = new SelectList(db.StoreDetails, "Id", "LoginId", storeKiosk.StoreDetailId);
            ViewBag.SettingId = new SelectList(SettingsTypes, "Value", "Text", storeKiosk.SettingId);
            ViewBag.StoreId = storeKiosk.StoreDetailId;
            return View(storeKiosk);
        }

        // POST: Admin/StoreKiosks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StoreDetailId,KioskName,SettingId")] StoreKiosk storeKiosk)
        {
            if (ModelState.IsValid)
            {
                if (store.AdminMgr.EditStoreKiosk(storeKiosk))
                    return RedirectToAction("Details", "StoreDetails", new { id = storeKiosk.StoreDetailId });
            }
            ViewBag.StoreDetailId = new SelectList(db.StoreDetails, "Id", "LoginId", storeKiosk.StoreDetailId);
            ViewBag.SettingId = new SelectList(SettingsTypes, "Value", "Text", storeKiosk.SettingId);
            ViewBag.StoreId = storeKiosk.StoreDetailId;
            return View(storeKiosk);
        }

        // GET: Admin/StoreKiosks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StoreKiosk storeKiosk = store.AdminMgr.GetStoreKiosk((int)id);
            if (storeKiosk == null)
            {
                return HttpNotFound();
            }
            return View(storeKiosk);
        }

        // POST: Admin/StoreKiosks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StoreKiosk storeKiosk = store.AdminMgr.GetStoreKiosk((int)id);
            if (store.AdminMgr.RemoveStoreKiosk(storeKiosk))
                return RedirectToAction("Details", "StoreDetails", new { id = storeKiosk.StoreDetailId });
            return View(storeKiosk);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                store.AdminMgr.DbDispose();
            }
            base.Dispose(disposing);
        }
    }
}

eCart/Areas/Admin/Views/StoreDetails/Create.cshtml
@model eCartModels.StoreDetail

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StoreDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LoginId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.LoginId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("LoginId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LoginId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StoreStatusId, "StoreStatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StoreStatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StoreStatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StoreCategoryId, "StoreCategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StoreCategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StoreCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MasterCityId, "MasterCityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MasterCityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MasterCityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MasterAreaId, "MasterAreaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MasterAreaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MasterAreaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eCart/Areas/Admin/Views/StoreDetails/Delete.cshtml
@model eCartModels.StoreDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StoreDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MasterArea.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MasterArea.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MasterCity.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MasterCity.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StoreCategory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoreCategory.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StoreStatu.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoreStatu.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoginId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoginId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

eCart/Areas/Admin/Views/StoreDetails/Details.cshtml
@model eCartModels.StoreDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div class="row panel bordered" style="padding:10px 20px; ">
    <div class="col-lg-12">
        <h2> @Model.Name </h2>

        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>

        <hr />
    </div>
    <div class="col-lg-6">
        <div class="control-label">
            <label class="text-muted"> Address: </label>
            <label> @Model.Address  </label>
        </div>
        <div class="control-label">
            <label class="text-muted"> Category: </label>
            <label> @Model.StoreCategory.Name  </label>
        </div>

        <div class="control-label">
            <label class="text-muted"> LoginId: </label>
            <label> @Model.LoginId  </label>
        </div>
        <div class="control-label">
            <label class="text-muted"> Remarks: </label>
            <label> @Model.Remarks  </label>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="control-label">
            <label class="text-muted"> Area: </label>
            <label> @Model.MasterArea.Name  </label>
        </div>
        <div class="control-label">
            <label class="text-muted"> City: </label>
            <label> @Model.MasterCity.Name  </label>
        </div>

        <div class="control-label">
            <label class="text-muted"> Status: </label>
            <label> @Model.StoreStatu.Name  </label>
        </div>
    </div>
    <div class="col-lg-12">
        <hr />
    </div>
    <div class="col-lg-12">
        <h3> Store Kiosks </h3>

        @Html.ActionLink("Create Kiosk", "Create", "StoreKiosks", new { id = Model.Id }, null)
        <table class="table ">
            <thead>
                <tr>
                    <th> Kiosk Name  </th>
                    <th> Settings ID  </th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var kiosk in ViewBag.StoreKiosks as IEnumerable<eCartModels.StoreKiosk>)
                {
                    <tr>
                        <td> @kiosk.KioskName </td>
                        <td> @kiosk.SettingId </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "StoreKiosks", new { id = kiosk.Id }, null) |

                            @Html.ActionLink("Delete", "Delete", "StoreKiosks", new { id = kiosk.Id }, null)
                        </td>
                    </tr>
                }
            </tbody>

        </table>

    </div>
</div>

eCart/Areas/Admin/Views/StoreDetails/Edit.cshtml
@model eCartModels.StoreDetail

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StoreDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.LoginId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.LoginId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("LoginId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LoginId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StoreStatusId, "StoreStatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StoreStatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StoreStatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StoreCategoryId, "StoreCategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StoreCategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StoreCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MasterCityId, "MasterCityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MasterCityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MasterCityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MasterAreaId, "MasterAreaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MasterAreaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MasterAreaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eCart/Areas/Admin/Views/StoreDetails/Index.cshtml
@model IEnumerable<eCartModels.StoreDetail>

@{
    ViewBag.Title = "Store Lists";
}

<h2>Store Lists</h2>

<p>
    @Html.ActionLink("Back to Dashboard", "Index", "Dashboard") |
    @Html.ActionLink("Create New", "Create")
</p>
<div class="panel bordered">
    <div>
        <table class="table">
            <tr>
                <th>
                     Store&nbsp;Name
                </th>
                <th>
                    Area
                </th>
                <th>
                    City
                </th>
                <th>
                    Category
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    Status
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Remarks)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <span class="table-data-primary-text text-primary">@Html.DisplayFor(modelItem => item.Name)</span>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MasterArea.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MasterCity.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StoreCategory.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StoreStatu.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Remarks)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>